# Generated by Django 5.0.4 on 2024-04-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Brand',
        ),
    ]
