# Generated by Django 5.0.4 on 2024-04-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_collection_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='featured_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_product', to='store.product'),
        ),
    ]
