# Generated by Django 5.0.4 on 2024-04-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_brand_featured_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_category',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default='Default Description', null=True),
        ),
        migrations.AddField(
            model_name='main_category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
