# Generated by Django 5.0.4 on 2024-04-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_main_category_descriptions_brand_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
