# Generated by Django 5.0.4 on 2024-04-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_brand_active_alter_main_category_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collection',
            new_name='brand',
        ),
    ]
