# Generated by Django 5.0.4 on 2024-05-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_street_address_state_address_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
