# Generated by Django 5.0.4 on 2024-05-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
    ]
