# Generated by Django 5.0.4 on 2024-05-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='store.address'),
            preserve_default=False,
        ),
    ]
