# Generated by Django 5.0.6 on 2024-05-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_coupon_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PL', 'Placed'), ('SH', 'Shipped'), ('DL', 'Delivered'), ('CA', 'Cancelled'), ('RR', 'Return Requested'), ('RA', 'Return Approved'), ('RC', 'Return Received'), ('RP', 'Return Processed')], default='PL', max_length=2),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
