# Generated by Django 5.0.6 on 2024-05-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_order_status_alter_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('rzr', 'Razorpay')], default='cod', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PL', 'Placed'), ('FL', 'Failed'), ('SH', 'Shipped'), ('DL', 'Delivered'), ('CA', 'Cancelled'), ('RR', 'Return Requested'), ('RA', 'Return Approved'), ('RC', 'Return Received'), ('RP', 'Return Processed')], default='PL', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], max_length=1),
        ),
    ]
