# Generated by Django 5.0.6 on 2024-05-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_order_payment_method_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rzr_order_id', models.CharField(max_length=500)),
                ('rzr_payment_id', models.CharField(max_length=500)),
                ('rzr_signature', models.CharField(max_length=500)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='razor_orders', to='store.order')),
            ],
        ),
    ]
