# Generated by Django 5.0.6 on 2024-05-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_razorpayorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpayorders',
            name='rzr_order_id',
        ),
        migrations.AlterField(
            model_name='razorpayorders',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='razorpayorders',
            name='rzr_payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayorders',
            name='rzr_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
