# Generated by Django 5.0.6 on 2024-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_order_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_at', '-placed_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CA', 'Cancelled'), ('RC', 'Return Received'), ('SH', 'Shipped'), ('DL', 'Delivered'), ('RR', 'Return Requested'), ('RA', 'Return Approved'), ('RP', 'Return Processed'), ('FL', 'Failed'), ('PL', 'Placed')], default='PL', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], max_length=1),
        ),
    ]
