# Generated by Django 5.0.6 on 2024-05-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_orderaddress_wallet_updated_at_alter_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='title',
        ),
    ]
