# Generated by Django 5.0.6 on 2024-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_product_discount_branddiscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
