# Generated by Django 5.0.6 on 2024-06-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_orderitem_status_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_at', '-order_status', '-placed_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PL', 'Placed'), ('PR', 'Processing'), ('CO', 'Completed'), ('CA', 'Cancelled'), ('FL', 'Failed'), ('SH', 'Shipped'), ('DL', 'Delivered'), ('RE', 'Returned')], default='PL', max_length=2),
        ),
    ]
