# Generated by Django 5.0.6 on 2024-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_order_options_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PL', 'Placed'), ('PR', 'Processing'), ('CA', 'Cancelled'), ('FL', 'Failed'), ('DL', 'Delivered'), ('RE', 'Returned'), ('CO', 'Completed'), ('RR', 'Return Requested')], default='PL', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Cancelled'), ('RR', 'Return Requested'), ('RA', 'Return Approved'), ('S', 'Shipped'), ('D', 'Delivered'), ('RE', 'Returned')], default='P', max_length=2),
        ),
    ]
