# Generated by Django 5.0.6 on 2024-06-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_order_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
