# Generated by Django 5.0.6 on 2024-06-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.DeleteModel(
            name='ReferralOffer',
        ),
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
