# Generated by Django 5.0.6 on 2024-06-26 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_product_offer_end_product_offer_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_category',
            name='offer_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main_category',
            name='offer_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='main_category',
            name='offer_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
