# Generated by Django 5.0.6 on 2024-06-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='store/categories'),
        ),
    ]
