# Generated by Django 5.0.4 on 2024-04-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
