# Generated by Django 5.0.4 on 2024-05-06 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='email',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='otp_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
